// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuoawzlabmwhvfcahcfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1b2F3emxhYm13aHZmY2FoY2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTcyNTAsImV4cCI6MjA3MTI5MzI1MH0.kRegPt6oYxMmQiXqMc8freQdmS-UKtqDJHbnw4LZ-WQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});